### ISSUE TITLE
Playlist Import Memory Clear Broken

### ISSUE THREAD

**Issue by KellethDregar** [p4535992/foundryvtt-playlist-import#4]
**Module Version:** v1.8.3

**Describe the bug**
Not sure if the memory clear button is meant to be functional but the button looks a bit broken, additionally when clicked it opens the dialog which throws errors on each interaction. Clear, cancel and X all fail. Included screenshots of the console error below.

**To Reproduce**
1. Click the "Playlist-Importer Memory Clear"
2. Click any of the buttons and attempt to close the dialog box
3. See error

**Expected behavior**
Dialog box works and clears songs out of memory or closes normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/79947702/209417465-032d386f-025e-4163-891e-cf9cae2009a6.png)

**Browser:**
 - Google Chrome

**Foundry Version:** 
v10.291

**Game System:** 
Dnd5e

**Comment by p4535992** [comment]
Should be fixed with 1.8.5
